version: '3'

services:
  # Application

  mongo:
    image: 'bitnami/mongodb:latest'
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=empresta
      - MONGODB_PASSWORD=mongo_password_development
      - MONGODB_DATABASE=empresta-challenge-crawler
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
